spring:
  application:
    name: ai-service
  ai:
    ollama:
      base-url: http://localhost:11434
      chat:
        model: gemma3:270m
server:
  port: 8083

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true
    enabled: true